// src/lib/podcastFeed.ts
//
// WHY: The podcast page originally embedded Buzzsprout's own "small
// player" widget wholesale (one <script>, no content modeling at all)
// — zero migration work, but its markup is a fixed black box: no way
// to shrink the cards or group episodes by month (Curtis's ask,
// 2026-09-14). Buzzsprout also publishes a completely public,
// no-auth-needed RSS feed with real structured per-episode data
// (title, date, duration, cover image, summary, audio file URL) — this
// fetches and parses that feed at build time, same "fetch external
// data, render it ourselves" shape every other page already uses for
// Sanity content, just a different source. Still zero manual episode
// entry and still auto-updates on every rebuild whenever a new episode
// publishes — the whole point of not hand-modeling this in Sanity.
//
// A plain regex-based parser, not a full XML/RSS library: Buzzsprout's
// feed is generated by one program (not hand-authored XML that could
// vary in whitespace/structure/nesting), and RSS <item> elements never
// nest, so splitting on <item>...</item> and pulling known tags out of
// each chunk is reliable here without pulling in a dependency for it.

const FEED_URL = 'https://feeds.buzzsprout.com/2007861.rss'

export interface PodcastFeedEpisode {
  id: string
  title: string
  summary: string
  publishedAt: Date
  durationSeconds: number
  imageUrl: string | null
  audioUrl: string
  episodeNumber: number | null
  season: number | null
}

// Covers everything actually observed in this feed (titles/summaries
// use &amp; and curly quotes/em-dashes as literal UTF-8, not entities)
// plus the other four XML-predefined entities and numeric refs, for
// safety against future episode titles this hasn't seen yet.
function decodeEntities(text: string): string {
  return text
    .replace(/&#(\d+);/g, (_, dec) => String.fromCharCode(Number(dec)))
    .replace(/&#x([0-9a-fA-F]+);/g, (_, hex) => String.fromCharCode(parseInt(hex, 16)))
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
}

function tagText(xml: string, tag: string): string | null {
  // Opening tag allows attributes (e.g. <guid isPermaLink="false">) —
  // matched non-greedily up to the first `>`, not required to be bare.
  const match = xml.match(
    new RegExp(`<${tag}[^>]*>\\s*(?:<!\\[CDATA\\[([\\s\\S]*?)\\]\\]>|([\\s\\S]*?))\\s*</${tag}>`),
  )
  if (!match) return null
  return decodeEntities((match[1] ?? match[2] ?? '').trim())
}

function tagAttr(xml: string, tag: string, attr: string): string | null {
  const match = xml.match(new RegExp(`<${tag}[^>]*\\s${attr}="([^"]*)"[^>]*/?>`))
  return match ? decodeEntities(match[1]) : null
}

/** Buzzsprout's summary is a truncated (often mid-sentence, ending in
 * "...") plain-text field meant for exactly this kind of card use —
 * the full <description>/<content:encoded> is the same text
 * untruncated plus HTML paragraph tags, not a separate longer piece of
 * writing, so there's no richer "real" excerpt being left on the
 * table by using it as-is. */
function parseItem(xml: string): PodcastFeedEpisode | null {
  const guid = tagText(xml, 'guid')
  const title = tagText(xml, 'title')
  const pubDate = tagText(xml, 'pubDate')
  const audioUrl = tagAttr(xml, 'enclosure', 'url')
  if (!guid || !title || !pubDate || !audioUrl) return null

  const durationRaw = tagText(xml, 'itunes:duration') ?? '0'
  // itunes:duration is usually plain seconds ("888") but the spec also
  // allows "HH:MM:SS"/"MM:SS" — handle both since nothing guarantees
  // Buzzsprout never switches formats.
  const durationSeconds = durationRaw.includes(':')
    ? durationRaw.split(':').reduce((acc, part) => acc * 60 + Number(part), 0)
    : Number(durationRaw) || 0

  const episodeRaw = tagText(xml, 'itunes:episode')
  const seasonRaw = tagText(xml, 'itunes:season')

  return {
    id: guid,
    title,
    summary: tagText(xml, 'itunes:summary') ?? '',
    publishedAt: new Date(pubDate),
    durationSeconds,
    imageUrl: tagAttr(xml, 'itunes:image', 'href'),
    audioUrl,
    episodeNumber: episodeRaw ? Number(episodeRaw) : null,
    season: seasonRaw ? Number(seasonRaw) : null,
  }
}

/** Newest first — matches the feed's own natural order, but sorted
 * explicitly rather than trusted, since nothing about "grouped by
 * month" holds up if a feed refresh ever reorders items. */
export async function getPodcastEpisodes(): Promise<PodcastFeedEpisode[]> {
  const res = await fetch(FEED_URL)
  if (!res.ok) throw new Error(`Buzzsprout feed fetch failed: ${res.status} ${res.statusText}`)
  const xml = await res.text()
  const items = xml.match(/<item>[\s\S]*?<\/item>/g) ?? []
  return items
    .map(parseItem)
    .filter((ep): ep is PodcastFeedEpisode => ep !== null)
    .sort((a, b) => b.publishedAt.getTime() - a.publishedAt.getTime())
}

/** "September 2026" — the grouping key AND label for a month section
 * on the podcast page. */
export function monthLabel(date: Date): string {
  return date.toLocaleDateString('en-US', { month: 'long', year: 'numeric', timeZone: 'UTC' })
}

/** 888 -> "14:48"; pads seconds only (a 62-minute episode reads as
 * "62:03", not "1:02:03" — every episode in this feed so far is under
 * an hour, and un-padded hour math isn't worth adding for a case that
 * may never occur). */
export function formatDuration(totalSeconds: number): string {
  const minutes = Math.floor(totalSeconds / 60)
  const seconds = Math.round(totalSeconds % 60)
  return `${minutes}:${String(seconds).padStart(2, '0')}`
}
